spring.application.name=expense

# The exact connection configurations to your local pgAdmin database
spring.datasource.url=jdbc:postgresql://localhost:5432/Temp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Instructs Hibernate to update your tables dynamically at runtime
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
